name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  check_run:
    types:
      - completed
  issue_comment:
    types:
      - created
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.WORKFLOW_TOKEN }}"
          MERGE_LABELS: "automerge,ready"
          MERGE_REMOVE_LABELS: "automerge,ready,updated,ok"
          MERGE_METHOD: "merge"
          MERGE_METHOD_LABELS: "automerge=merge,ready=merge,autosquash=squash,autorebose=rebose"
          MERGE_METHOD_LABEL_REQUIRED: true
          MERGE_COMMIT_MESSAGE: "pull-request-title-and-description"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_REQUIRED_APPROVALS: "0"
          MERGE_DELETE_BRANCH: true
          MERGE_DELETE_BRANCH_FILTER: ""
          MERGE_ERROR_FAIL: true
          UPDATE_LABELS: "updated,ok"
          UPDATE_METHOD: "merge"
          UPDATE_RETRIES: "6"
          UPDATE_RETRY_SLEEP: "10000"
#         PULL_REQUEST: ""
#         BASE_BRANCHES: ""

