name: Merge me!

on:
  pull_request_target:
    branches:
      main
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  check_suite:
    types:
      - completed
jobs:
  merge-me:
    name: Merge me!
    runs-on: ubuntu-latest
    steps:
      - name: Merge me! ImgBotApp
        if: ${{ github.actor == 'imgbot' }}
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_LOGIN: imgbot
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          ENABLE_GITHUB_API_PREVIEW: true
          MERGE_METHOD: MERGE
          MAXIMUM_RETRIES: 3
          ENABLED_FOR_MANUAL_CHANGES: 'true'
      - name: Merge me! deepsourcebot
        if: ${{ github.actor == 'deepsourcebot' }}
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_LOGIN: deepsourcebot
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          ENABLE_GITHUB_API_PREVIEW: true
          MERGE_METHOD: MERGE
          MAXIMUM_RETRIES: 3
          ENABLED_FOR_MANUAL_CHANGES: 'true'
      - name: Merge me! renovate[bot]
        if: ${{ github.actor == 'renovate[bot]' }}
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_LOGIN: renovate
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          ENABLE_GITHUB_API_PREVIEW: true
          MERGE_METHOD: MERGE
          MAXIMUM_RETRIES: 3
          ENABLED_FOR_MANUAL_CHANGES: 'true'
      - name: Merge me! dependabot[bot]
        if: ${{ github.actor == 'dependabot[bot]' }}
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_LOGIN: dependabot
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          PRESET: DEPENDABOT_PATCH
          ENABLE_GITHUB_API_PREVIEW: true
          MERGE_METHOD: MERGE
          MAXIMUM_RETRIES: 3
          ENABLED_FOR_MANUAL_CHANGES: 'true'
      - name: Merge me! Owner
        if: ${{ github.actor == 'dioapw' }}
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_LOGIN: dioapw
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          ENABLE_GITHUB_API_PREVIEW: true
          MERGE_METHOD: MERGE
          MAXIMUM_RETRIES: 3
          ENABLED_FOR_MANUAL_CHANGES: 'true'
